#!/usr/bin/env python
"""Write the Windows Startup launcher for rtx-bridge.

WScript reads .vbs files as ANSI, not UTF-8. This repo lives at C:\\<ae>, and a
UTF-8 .vbs holding that path is decoded into mojibake, so the launch dies with
"The system cannot find the path specified" while still reporting rc=0. Writing
UTF-16LE with a BOM is what WScript reads correctly.

Two path flavours are also required:
  - WScript must OPEN bash.exe         -> native Windows form (C:\\...\\bash.exe)
  - bash -lc must PARSE the script arg -> MSYS form (/c/.../rtx-bridge.sh)
Handing bash the native form makes it eat the backslashes and nothing runs.

Usage: rtx_bridge_startup.py <vbs_output_path> <bash_exe_native> <script_msys>
"""
import sys

vbs_path, bash_exe, script = sys.argv[1], sys.argv[2], sys.argv[3]

lines = [
    "' ae://rtx-bridge - launch the Victus RTX hands at login, hidden.",
    "' generated by rtx-bridge.sh startup - written UTF-16LE (WScript reads .vbs as ANSI)",
    'Set sh = CreateObject("WScript.Shell")',
    'sh.Run """%s"" -lc ""\'%s\' up", 0, False' % (bash_exe, script),
]

body = "\r\n".join(lines) + "\r\n"

# UTF-16LE + BOM. WScript honours the BOM and decodes the file correctly.
with open(vbs_path, "wb") as fh:
    fh.write(b"\xff\xfe" + body.encode("utf-16-le"))

print("wrote %s (%d bytes, UTF-16LE+BOM)" % (vbs_path, len(body) * 2 + 2))
